global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'circuitbreaker-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['circuitbreaker-demo:8080']
        labels:
          application: circuitbreaker-demo